/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubImport } from './routes/sub'
import { Route as SqrtImport } from './routes/sqrt'
import { Route as SortImport } from './routes/sort'
import { Route as RoundImport } from './routes/round'
import { Route as QuartileImport } from './routes/quartile'
import { Route as PipeImport } from './routes/pipe'
import { Route as MulImport } from './routes/mul'
import { Route as MinImport } from './routes/min'
import { Route as MeanImport } from './routes/mean'
import { Route as MaxImport } from './routes/max'
import { Route as MadImport } from './routes/mad'
import { Route as IsLeftGreaterOrEqualImport } from './routes/isLeftGreaterOrEqual'
import { Route as IsLeftGreaterImport } from './routes/isLeftGreater'
import { Route as IsEqualImport } from './routes/isEqual'
import { Route as IqrImport } from './routes/iqr'
import { Route as InstallImport } from './routes/install'
import { Route as DivImport } from './routes/div'
import { Route as AddImport } from './routes/add'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SubRoute = SubImport.update({
  id: '/sub',
  path: '/sub',
  getParentRoute: () => rootRoute,
} as any)

const SqrtRoute = SqrtImport.update({
  id: '/sqrt',
  path: '/sqrt',
  getParentRoute: () => rootRoute,
} as any)

const SortRoute = SortImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => rootRoute,
} as any)

const RoundRoute = RoundImport.update({
  id: '/round',
  path: '/round',
  getParentRoute: () => rootRoute,
} as any)

const QuartileRoute = QuartileImport.update({
  id: '/quartile',
  path: '/quartile',
  getParentRoute: () => rootRoute,
} as any)

const PipeRoute = PipeImport.update({
  id: '/pipe',
  path: '/pipe',
  getParentRoute: () => rootRoute,
} as any)

const MulRoute = MulImport.update({
  id: '/mul',
  path: '/mul',
  getParentRoute: () => rootRoute,
} as any)

const MinRoute = MinImport.update({
  id: '/min',
  path: '/min',
  getParentRoute: () => rootRoute,
} as any)

const MeanRoute = MeanImport.update({
  id: '/mean',
  path: '/mean',
  getParentRoute: () => rootRoute,
} as any)

const MaxRoute = MaxImport.update({
  id: '/max',
  path: '/max',
  getParentRoute: () => rootRoute,
} as any)

const MadRoute = MadImport.update({
  id: '/mad',
  path: '/mad',
  getParentRoute: () => rootRoute,
} as any)

const IsLeftGreaterOrEqualRoute = IsLeftGreaterOrEqualImport.update({
  id: '/isLeftGreaterOrEqual',
  path: '/isLeftGreaterOrEqual',
  getParentRoute: () => rootRoute,
} as any)

const IsLeftGreaterRoute = IsLeftGreaterImport.update({
  id: '/isLeftGreater',
  path: '/isLeftGreater',
  getParentRoute: () => rootRoute,
} as any)

const IsEqualRoute = IsEqualImport.update({
  id: '/isEqual',
  path: '/isEqual',
  getParentRoute: () => rootRoute,
} as any)

const IqrRoute = IqrImport.update({
  id: '/iqr',
  path: '/iqr',
  getParentRoute: () => rootRoute,
} as any)

const InstallRoute = InstallImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRoute,
} as any)

const DivRoute = DivImport.update({
  id: '/div',
  path: '/div',
  getParentRoute: () => rootRoute,
} as any)

const AddRoute = AddImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddImport
      parentRoute: typeof rootRoute
    }
    '/div': {
      id: '/div'
      path: '/div'
      fullPath: '/div'
      preLoaderRoute: typeof DivImport
      parentRoute: typeof rootRoute
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallImport
      parentRoute: typeof rootRoute
    }
    '/iqr': {
      id: '/iqr'
      path: '/iqr'
      fullPath: '/iqr'
      preLoaderRoute: typeof IqrImport
      parentRoute: typeof rootRoute
    }
    '/isEqual': {
      id: '/isEqual'
      path: '/isEqual'
      fullPath: '/isEqual'
      preLoaderRoute: typeof IsEqualImport
      parentRoute: typeof rootRoute
    }
    '/isLeftGreater': {
      id: '/isLeftGreater'
      path: '/isLeftGreater'
      fullPath: '/isLeftGreater'
      preLoaderRoute: typeof IsLeftGreaterImport
      parentRoute: typeof rootRoute
    }
    '/isLeftGreaterOrEqual': {
      id: '/isLeftGreaterOrEqual'
      path: '/isLeftGreaterOrEqual'
      fullPath: '/isLeftGreaterOrEqual'
      preLoaderRoute: typeof IsLeftGreaterOrEqualImport
      parentRoute: typeof rootRoute
    }
    '/mad': {
      id: '/mad'
      path: '/mad'
      fullPath: '/mad'
      preLoaderRoute: typeof MadImport
      parentRoute: typeof rootRoute
    }
    '/max': {
      id: '/max'
      path: '/max'
      fullPath: '/max'
      preLoaderRoute: typeof MaxImport
      parentRoute: typeof rootRoute
    }
    '/mean': {
      id: '/mean'
      path: '/mean'
      fullPath: '/mean'
      preLoaderRoute: typeof MeanImport
      parentRoute: typeof rootRoute
    }
    '/min': {
      id: '/min'
      path: '/min'
      fullPath: '/min'
      preLoaderRoute: typeof MinImport
      parentRoute: typeof rootRoute
    }
    '/mul': {
      id: '/mul'
      path: '/mul'
      fullPath: '/mul'
      preLoaderRoute: typeof MulImport
      parentRoute: typeof rootRoute
    }
    '/pipe': {
      id: '/pipe'
      path: '/pipe'
      fullPath: '/pipe'
      preLoaderRoute: typeof PipeImport
      parentRoute: typeof rootRoute
    }
    '/quartile': {
      id: '/quartile'
      path: '/quartile'
      fullPath: '/quartile'
      preLoaderRoute: typeof QuartileImport
      parentRoute: typeof rootRoute
    }
    '/round': {
      id: '/round'
      path: '/round'
      fullPath: '/round'
      preLoaderRoute: typeof RoundImport
      parentRoute: typeof rootRoute
    }
    '/sort': {
      id: '/sort'
      path: '/sort'
      fullPath: '/sort'
      preLoaderRoute: typeof SortImport
      parentRoute: typeof rootRoute
    }
    '/sqrt': {
      id: '/sqrt'
      path: '/sqrt'
      fullPath: '/sqrt'
      preLoaderRoute: typeof SqrtImport
      parentRoute: typeof rootRoute
    }
    '/sub': {
      id: '/sub'
      path: '/sub'
      fullPath: '/sub'
      preLoaderRoute: typeof SubImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/div': typeof DivRoute
  '/install': typeof InstallRoute
  '/iqr': typeof IqrRoute
  '/isEqual': typeof IsEqualRoute
  '/isLeftGreater': typeof IsLeftGreaterRoute
  '/isLeftGreaterOrEqual': typeof IsLeftGreaterOrEqualRoute
  '/mad': typeof MadRoute
  '/max': typeof MaxRoute
  '/mean': typeof MeanRoute
  '/min': typeof MinRoute
  '/mul': typeof MulRoute
  '/pipe': typeof PipeRoute
  '/quartile': typeof QuartileRoute
  '/round': typeof RoundRoute
  '/sort': typeof SortRoute
  '/sqrt': typeof SqrtRoute
  '/sub': typeof SubRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/div': typeof DivRoute
  '/install': typeof InstallRoute
  '/iqr': typeof IqrRoute
  '/isEqual': typeof IsEqualRoute
  '/isLeftGreater': typeof IsLeftGreaterRoute
  '/isLeftGreaterOrEqual': typeof IsLeftGreaterOrEqualRoute
  '/mad': typeof MadRoute
  '/max': typeof MaxRoute
  '/mean': typeof MeanRoute
  '/min': typeof MinRoute
  '/mul': typeof MulRoute
  '/pipe': typeof PipeRoute
  '/quartile': typeof QuartileRoute
  '/round': typeof RoundRoute
  '/sort': typeof SortRoute
  '/sqrt': typeof SqrtRoute
  '/sub': typeof SubRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/div': typeof DivRoute
  '/install': typeof InstallRoute
  '/iqr': typeof IqrRoute
  '/isEqual': typeof IsEqualRoute
  '/isLeftGreater': typeof IsLeftGreaterRoute
  '/isLeftGreaterOrEqual': typeof IsLeftGreaterOrEqualRoute
  '/mad': typeof MadRoute
  '/max': typeof MaxRoute
  '/mean': typeof MeanRoute
  '/min': typeof MinRoute
  '/mul': typeof MulRoute
  '/pipe': typeof PipeRoute
  '/quartile': typeof QuartileRoute
  '/round': typeof RoundRoute
  '/sort': typeof SortRoute
  '/sqrt': typeof SqrtRoute
  '/sub': typeof SubRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/div'
    | '/install'
    | '/iqr'
    | '/isEqual'
    | '/isLeftGreater'
    | '/isLeftGreaterOrEqual'
    | '/mad'
    | '/max'
    | '/mean'
    | '/min'
    | '/mul'
    | '/pipe'
    | '/quartile'
    | '/round'
    | '/sort'
    | '/sqrt'
    | '/sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/div'
    | '/install'
    | '/iqr'
    | '/isEqual'
    | '/isLeftGreater'
    | '/isLeftGreaterOrEqual'
    | '/mad'
    | '/max'
    | '/mean'
    | '/min'
    | '/mul'
    | '/pipe'
    | '/quartile'
    | '/round'
    | '/sort'
    | '/sqrt'
    | '/sub'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/div'
    | '/install'
    | '/iqr'
    | '/isEqual'
    | '/isLeftGreater'
    | '/isLeftGreaterOrEqual'
    | '/mad'
    | '/max'
    | '/mean'
    | '/min'
    | '/mul'
    | '/pipe'
    | '/quartile'
    | '/round'
    | '/sort'
    | '/sqrt'
    | '/sub'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  DivRoute: typeof DivRoute
  InstallRoute: typeof InstallRoute
  IqrRoute: typeof IqrRoute
  IsEqualRoute: typeof IsEqualRoute
  IsLeftGreaterRoute: typeof IsLeftGreaterRoute
  IsLeftGreaterOrEqualRoute: typeof IsLeftGreaterOrEqualRoute
  MadRoute: typeof MadRoute
  MaxRoute: typeof MaxRoute
  MeanRoute: typeof MeanRoute
  MinRoute: typeof MinRoute
  MulRoute: typeof MulRoute
  PipeRoute: typeof PipeRoute
  QuartileRoute: typeof QuartileRoute
  RoundRoute: typeof RoundRoute
  SortRoute: typeof SortRoute
  SqrtRoute: typeof SqrtRoute
  SubRoute: typeof SubRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  DivRoute: DivRoute,
  InstallRoute: InstallRoute,
  IqrRoute: IqrRoute,
  IsEqualRoute: IsEqualRoute,
  IsLeftGreaterRoute: IsLeftGreaterRoute,
  IsLeftGreaterOrEqualRoute: IsLeftGreaterOrEqualRoute,
  MadRoute: MadRoute,
  MaxRoute: MaxRoute,
  MeanRoute: MeanRoute,
  MinRoute: MinRoute,
  MulRoute: MulRoute,
  PipeRoute: PipeRoute,
  QuartileRoute: QuartileRoute,
  RoundRoute: RoundRoute,
  SortRoute: SortRoute,
  SqrtRoute: SqrtRoute,
  SubRoute: SubRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add",
        "/div",
        "/install",
        "/iqr",
        "/isEqual",
        "/isLeftGreater",
        "/isLeftGreaterOrEqual",
        "/mad",
        "/max",
        "/mean",
        "/min",
        "/mul",
        "/pipe",
        "/quartile",
        "/round",
        "/sort",
        "/sqrt",
        "/sub"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add": {
      "filePath": "add.tsx"
    },
    "/div": {
      "filePath": "div.tsx"
    },
    "/install": {
      "filePath": "install.tsx"
    },
    "/iqr": {
      "filePath": "iqr.tsx"
    },
    "/isEqual": {
      "filePath": "isEqual.tsx"
    },
    "/isLeftGreater": {
      "filePath": "isLeftGreater.tsx"
    },
    "/isLeftGreaterOrEqual": {
      "filePath": "isLeftGreaterOrEqual.tsx"
    },
    "/mad": {
      "filePath": "mad.tsx"
    },
    "/max": {
      "filePath": "max.tsx"
    },
    "/mean": {
      "filePath": "mean.tsx"
    },
    "/min": {
      "filePath": "min.tsx"
    },
    "/mul": {
      "filePath": "mul.tsx"
    },
    "/pipe": {
      "filePath": "pipe.tsx"
    },
    "/quartile": {
      "filePath": "quartile.tsx"
    },
    "/round": {
      "filePath": "round.tsx"
    },
    "/sort": {
      "filePath": "sort.tsx"
    },
    "/sqrt": {
      "filePath": "sqrt.tsx"
    },
    "/sub": {
      "filePath": "sub.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
